require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
