require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - examples/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Naming/FileName:
  Exclude:
    - "lib/nylas-streaming.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
