inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - examples/**/*
    - vendor/**/*
    - gemfiles/vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - "lib/nylas/calendar_collection.rb"

Metrics/ClassLength:
  Exclude:
    - "lib/nylas/api.rb"
    - "lib/nylas/collection.rb"


Metrics/ModuleLength:
  Exclude:
    - "lib/nylas/model.rb"

Naming/FileName:
  Exclude:
    - "lib/nylas-streaming.rb"

Naming/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
