inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - examples/**/*
    - vendor/**/*
    - gemfiles/vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Metrics/ParameterLists:
  Max: 8

Naming/FileName:
  Exclude:
    - "lib/nylas-streaming.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
