language: ruby
rvm:
 - 2.2
 - 2.3
 - 2.4
cache: bundler
gemfile:
  - gemfiles/Gemfile.rails4
  - gemfiles/Gemfile.rails5
  - gemfiles/Gemfile.rest-client.1
  - gemfiles/Gemfile.rest-client.2
script: bundle exec rspec spec
