language: ruby
rvm:
 - 2.2
 - 2.3
 - 2.4
cache: bundler
gemfile:
  - gemfiles/Gemfile.rails4
  - gemfiles/Gemfile.rails5
  - gemfiles/Gemfile.rest-client.1
  - gemfiles/Gemfile.rest-client.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - CC_TEST_REPORTER_ID=d6eceb65e7832b7989705fe162ec290d311d9d37e4e1a653f30ad957a683253a
